### PR TITLE
Setting up automated tests and code coverage

### PR DESCRIPTION
**Pull request by phiferd**
This gets the project ready to use automated tests with truffle and code coverage with solidity-coverage.  I have added a sample test case to show how tests can be written.  Hopefully, others will contribute more tests to these contracts (esp MultiSig) as these are critical contracts and must be covered to avoid regressions.

### CODE REVIEW

**Comment by phiferd** [comment]
Here's a code coverage report I generated.  It only covers the Wallet.sol contract as that is the only contract I moved into the contracts directory.

image

**Comment by phiferd** [comment]
FYI, I copied the incresaeTime.js helper module from OpenZeppelin which is under the MIT license, although they don't have any copyright info in the file.  I've asked them (in their slack) if there is a blurb that can be included.

**Comment by keorn** [comment]
Cool! Still seems to require `truffle init` which puts in junk, otherwise I get `Could not find suitable configuration file.`

**Comment by phiferd** [comment]
This update should fix that issue.  Sorry about that.  A couple other things to note:

1. The OpenZeppelin folks didn't have any issue with increaseTime.js helper being used.  
2. package.json still references a forked version of solidity coverage. The have issued an update with a PR I sent it, but I haven't had a chance to revisit this.  

Also, if you guys can fix the CI build issues, that would be good.  If not, maybe just turn of the CI (altough I wouldn't recommend that route).  :)  I don't think they are related to my change, but please correct me if I'm wrong.

**Comment by keorn** [comment]
Yes, Im in the process of cleanup, will merge once compiling works.

**Comment by lght** [comment]
@philferd I just pulled down your changes, and couldn't get `truffle test` to run because `babel-registry` can't be found. prolly just a dumb npm bug, but did you have any similar issues?

keeping down the bloat from truffle is a great idea. do you know if anyone has reached out to them about a stripped-down version of just their test modules?

**Comment by phiferd** [comment]
> Keeping down the bloat from truffle is a great idea

I would rank that as a _very_ low priority relative to functional unit tests, actually.  It can happen in a subsequent commit.  I recommend consideration the following:

1. Get unit tests working (bloat or otherwise), with code coverage
2. Write tests for _all_ contracts (delete contracts that are not in use or broken)
3. Refactor contracts that are not **testable**.  Testability must be a design-time requirement, not an after-thought.  Contracts that require a hardcoded address of another contract on a specific network are not easily testable (unless you can get testrpc or similar to "mock" a contract at a particular address).
4. Put in place code-coverage requirements that are enforced on commit.  Look to best-practices around aerospace and banking software for reasonable line and branch coverage requirements.
5. With this in-place, feel free to clean up bloat with the guarantee that any changes will not impact correctness.

**Comment by lght** [comment]
> I would rank that as a very low priority relative to functional unit tests

Completely agree. I have had a change of heart after trying to write my own test, and attempting to get it to run with a far-from-normal configuration/setup. 

Getting functioning tests is way more important. I'll get everything running with your setup on my machine.

> Refactor contracts that are not testable ... (unless you can get testrpc or similar to "mock" a contract at a particular address)

This would be cool, and maybe there are some switches or hacks to get mocked addresses working. 

I am with you, though; refactoring contracts with hard-coded addresses is a simpler solution. Just a naive guess, but my feeling is that refactoring contracts to make them testable will also lead to better correctness as a side-effect.

**Comment by rphmeier** [comment]
#93 

I don't think truffle is ideal here because of the bloat it introduces. But it's definitely better than nothing.

**Pull request merged**
