### PR TITLE
Change Underlimit func

### PR DESCRIPTION
**Pull request by Hackdom**
Added the plus function from our BasicMathLib at Majoolr, more robust, gives the function a cleaner look, and function gives descriptive errors messages.

### CODE REVIEW

**Comment by Hackdom** [comment]
We run tests on all of our code at Majoolr in solidity ref the plus func, I feel it's more robust than the zep lib, we don't rely on a single point of expected op by the EVM in the case of overflow. Your call obviously, but if you have the time to check you can pull it down and analye from https://www.github.com/Majoolr/ethereum-libraries.

**Comment by rphmeier** [comment]
ensure indentation is using tabs to be consistent. also the body of `function plus` should be indented one level further and have a closing brace.

**Comment by Hackdom** [comment]
Working off a phone right now, I apologize. I put the indent in there, the if statement is a one liner so the last curly is the closing brace.

**Comment by Hackdom** [comment]
Curious as to why the Travis builds are failing.

**Comment by gavofyork** [comment]
it adds substantial complexity, yet since it's dealing with guaranteed ETH amounts `m_spentToday` and `_value`, there is precisely zero chance of overflow.

as such i'm not convinced it's worth it. open to persuasion...

**Comment by Hackdom** [comment]
There's no chance on overflow when defining the amounts within the wallet, but there is no bound to the value or spent parameter independently which either could theoretically be 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd ha, so I see your point, impossible? No, practical? Also no. I guess the only question is it appears this controls any token, not just ether, and there is a high probability of thousands of "penny" tokens which may drive numbers to overflow levels. My feelings won't be hurt either way, those are my thoughts.

**Comment by Hackdom** [comment]
I just invited the Alex folks on Reddit to come weigh in, hopefully get some more eyes on it.

**Comment by Ivshti** [comment]
@Hackdom I am also worried about the complexity here. We audited the code (https://github.com/paritytech/contracts/issues/69) and only found 2-3 places where the fear of math issues is significant, and all of them are OK. AFAIK tokens cannot be under the spending limit, as it only control wei (ether) ammounts. Tokens use a totally different mechanic. 

there is something unrelated though - transactions which control tokens are passed with value 0 and some data which executes a function in the token SC. This means that if the transaction has data, it has to go into multi-sig procedure so as to not allow single owner to drain tokens. This is implemented, but not commented (documented) in the code, therefore a bit confusing

Am I missing something?

**Comment by Hackdom** [comment]
Ok, I'll have to take a look later ref your question but reducing complexity is always beneficial so not a problem

**Comment by Hackdom** [comment]
I'll answer in the other branch and close this.

**Pull request closed without merging**
