### PR TITLE
Fix the License to be consistently APACHE 2.0 across all contracts.

### PR DESCRIPTION
**Pull request by 5chdn**
The repository was initialized with GPLv3, but contract headers suggest the source is licensed under APLv2.

This PR applies correct APLv2 headers to all `*.sol` Solidity source-code files. Overview:

    | Contract                                           | Current License    | This PR Change     | Authors & Contributors                               |
    | -------------------------------------------------- | ------------------ | ------------------ | ---------------------------------------------------- |
    | `ProofOfEmail.sol`                                 | APLv2              | _untouched_        | @gavofyork @derhuerst @keorn                         |
    | `Bounty.sol`                                       | APLv2              | _untouched_        | @gavofyork @derhuerst                                |
    | `DutchAuction.sol`                                 | APLv2              | _untouched_        | @gavofyork                                           |
    | `BasicCoin.sol`                                    | APLv2              | _untouched_        | @gavofyork @derhuerst @keorn @charlieknoll           |
    | `SimpleRegistry.sol`                               | APLv2              | _untouched_        | @gavofyork @derhuerst @keorn                         |
    | `contracts/Wallet.sol`                             | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @phiferd (@gavofyork) !                            |
    | `contracts/Migrations.sol`                         | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @phiferd !                                         |
    | `OprahBadge.sol`                                   | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @derhuerst @keorn !                                |
    | `Operations.sol`                                   | APLv2              | _untouched_        | @gavofyork @derhuerst                                |
    | `validator_contracts/InnerOwnedSet.sol`            | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/interfaces/Owned.sol`         | APLv2              | _untouched_        | @keorn (@gavofyork)                                  |
    | `validator_contracts/interfaces/ValidatorSet.sol`  | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/interfaces/RelaySet.sol`      | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/InnerTest.sol`                | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/libraries/AddressVotes.sol`   | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/Kovan.sol`                    | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/InnerMajoritySet.sol`         | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/OwnedSet.sol`                 | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/ImmediateTest.sol`            | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn @rphmeier !                                 |
    | `validator_contracts/Test.sol`                     | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `validator_contracts/MajoritySet.sol`              | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @keorn !                                           |
    | `Receipter.sol`                                    | APLv2              | _untouched_        | @gavofyork                                           |
    | `Owned.sol`                                        | APLv2              | _untouched_        | @gavofyork @keorn @rphmeier @derhuerst               |
    | `CoreVeto.sol`                                     | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @gavofyork @keorn !                                |
    | `GithubHint.sol`                                   | APLv2              | _untouched_        | @gavofyork @derhuerst                                |
    | `GavCoin.sol`                                      | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @gavofyork @derhuerst @jacogr @3esmit !            |
    | `TokenReg.sol`                                     | APLv2              | _untouched_        | @gavofyork @jacogr @keorn @derhuerst                 |
    | `Certifier.sol`                                    | APLv2              | _untouched_        | @gavofyork @keorn @derhuerst                         |
    | `DeadMansSwitch.sol`                               | APLv2 & MIT (dual) | _untouched_        | @gavofyork                                           |
    | `Registry.sol`                                     | APLv2              | _untouched_        | @gavofyork @keorn @ngotchac @derhuerst @jacogr       |
    | `SMSVerification.sol`                              | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @gavofyork @tomusdrw @rphmeier @keorn @derhuerst ! |
    | `KeyServerSet.sol`                                 | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @svyatonik @keorn (@gavofyork) !                   |
    | `TokenCalls.sol`                                   | APLv2              | _untouched_        | @ngotchac                                            |
    | `SignatureReg.sol`                                 | APLv2              | _untouched_        | @gavofyork @jacogr                                   |
    | `FairReceipter.sol`                                | APLv2              | _untouched_        | @gavofyork @rphmeier @keorn                          |
    | `Prism.sol`                                        | APLv2              | _untouched_        | @gavofyork @derhuerst                                |
    | `TimedDeposit.sol`                                 | APLv2              | _untouched_        | @gavofyork                                           |
    | `BadgeReg.sol`                                     | APLv2              | _untouched_        | @gavofyork @keorn @derhuerst                         |
    | `Token.sol`                                        | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @rphmeier @keorn !                                 |
    | `SimpleCertifier.sol`                              | APLv2              | _untouched_        | @gavofyork @keorn @derhuerst @bjornwgnr              |
    | `wallet/WalletLibrary.sol`                         | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @ngotchac (@gavofyork) !                           |
    | `wallet/WalletStub.sol`                            | APLv2 & MIT (dual) | _untouched_        | @ngotchac (@gavofyork)                               |
    | `DappReg.sol`                                      | APLv2              | _untouched_        | @gavofyork @jacogr @keorn                            |
    | `OperationsProxy.sol`                              | GPLv3 (inherited)  | **GPLv3 => APLv2** | ! @gavofyork !                                       |
    | `DutchBuyin.sol`                                   | APLv2              | _untouched_        | @gavofyork                                           |
    | `MasterCertifier.sol`                              | APLv2              | _untouched_        | @gavofyork @keorn                                    |

This PR can only be merged after the following authors and contributors explicitly agree the relicensing of their work (see above) to APLv2 (just comment to this PR to express your will):

- [x] @gavofyork
- [x] @jacogr
- [x] @keorn
- [x] @ngotchac
- [x] @rphmeier
- [x] @svyatonik
- [x] @tomusdrw
- [x] @derhuerst
- [x] @3esmit
- [x] @phiferd

Thanks!

### CODE REVIEW

**Comment by tomusdrw** [comment]
:+1:

**Comment by 3esmit** [comment]
Agreed.

**Comment by phiferd** [comment]
agreed

**Comment by jacogr** [comment]
Agreed.

**Comment by keorn** [comment]
Agree

**Comment by derhuerst** [comment]
👍

**Comment by rphmeier** [comment]
works for me!

**Comment by 5chdn** [comment]
Thanks everyone.

**Pull request merged**
