### PR TITLE
Add the Wallet Library

### PR DESCRIPTION
**Pull request by ngotchac**
Here's the wallet library, with the Wallet Stub contract. The stub contract will delegate every single call to the wallet library, even constant calls, and will return a `bytes32` result, which can then be converted to a `bool`, etc.
The idea is the keep the Wallet Stub contract as simple as possible ; it doesn't have any storage declaration, constant methods, etc, which should make update easier, and will be easier to verify. The Wallet Library should be as close as possible of the original Wallet : updates to the contract will be way easier. Here's the diff between the two :

```diff
--- Wallet.sol	2017-08-02 09:15:18.917198034 +0200
+++ wallet/WalletLibrary.sol	2017-08-15 18:01:21.213728851 +0200
@@ -51,11 +52,16 @@
 			_;
 	}
 
+	modifier only_uninitialized {
+		require(m_numOwners == 0);
+		_;
+	}
+
 	// METHODS
 
 	// constructor is given number of sigs required to do protected "onlymanyowners" transactions
 	// as well as the selection of addresses capable of confirming them.
-	function multiowned(address[] _owners, uint _required) {
+	function init_multiowned(address[] _owners, uint _required) only_uninitialized internal {
 		require(_required > 0);
 		require(_owners.length >= _required);
 		m_numOwners = _owners.length;
@@ -235,7 +241,7 @@
 	// METHODS
 
 	// constructor - stores initial daily limit and records the present day's index.
-	function daylimit(uint _limit) {
+	function init_daylimit(uint _limit) only_uninitialized internal {
 		m_dailyLimit = _limit;
 		m_lastDay = today();
 	}
@@ -313,7 +319,7 @@
 // usage:
 // bytes32 h = Wallet(w).from(oneOwner).execute(to, value, data);
 // Wallet(w).from(anotherOwner).confirm(h);
-contract Wallet is multisig, multiowned, daylimit, creator {
+contract WalletLibrary is multisig, multiowned, daylimit, creator {
 
 	// TYPES
 
@@ -328,8 +334,16 @@
 
 	// constructor - just pass on the owner array to the multiowned and
 	// the limit to daylimit
-	function Wallet(address[] _owners, uint _required, uint _daylimit)
-			multiowned(_owners, _required) daylimit(_daylimit) {
+	function WalletLibrary() {
+		address[] owners;
+
+		owners.push(address(0x0));
+		init_wallet(owners, 1, 0);
+	}
+
+	function init_wallet(address[] _owners, uint _required, uint _daylimit) only_uninitialized public {
+		init_daylimit(_daylimit);
+		init_multiowned(_owners, _required);
 	}
 
 	// kills the contract sending everything to `_to`.
```

### CODE REVIEW

**Comment by 3esmit** [comment]
Excellent, seems like a better approch then last one! I will grab some code for mine too :)

**Comment by 3esmit** [comment]
BTW, when you deploy WalletLibrary, the init function will be open in that contract. I recommend you calling initWallet on WalletLibrary right after its deploy, just to ensure no one will use it.

**Comment by 3esmit** [comment]
I think you should fix the "uint => uint" and other storages that are wrong. See #62

**Comment by ngotchac** [comment]
The goal of this PR is to have a Wallet Library and a Wallet Stub, where the Wallet Library is as close as possible to the Foundation Wallet. So even if the types could be tuned better, it's not the scope of this PR.

You're right about the init functions of the library ; even if it shouldn't harm, I'll fix that.

**Comment by 3esmit** [comment]
I had to make this changes https://github.com/status-im/commiteth/pull/84 to make it Web3js compatible, since it needs correct ABI for some reason, or it don't identifies.
also the assembly returns only fixed 0x20 values, so arrays wont work, then I had to include the array related logic to stub.
Have fun @ngotchac  :laughing:

**Comment by ngotchac** [comment]
Yep, array won't work, but in this Wallet contract, no arrays are returned (which isn't the best for building a proper UI, I agree...). Also I think I can still build the ABI from the non-stub Wallet contract, as it should be the same :) Thanks for you input though, great work ! Nice one using the modifier ;)

**Comment by 3esmit** [comment]
Would be possible to make it return arrays? I imagine that we could retrive the first 0x20 bytes that is the array size and then read the elements and return the proper data?

**Comment by elpinguinofrio** [comment]
"seems like a better approch" - better approach indeed.

**Comment by w0404210** [comment]
feels bad to not listen man

**Pull request merged**
