### PR TITLE
Fixes proposed

### PR DESCRIPTION
**Pull request by Hackdom**
Fix sloppy code and forgot internal again on the create function

### CODE REVIEW

**Comment by Hackdom** [comment]
Let me know if you have any questions

**Comment by gavofyork** [comment]
thanks for the work you put in.

this, however, should be split into several PRs. at least one for documentation and another several for each of the individual parts of logic altered. there are some changes that are (at least on initial review) highly sensitive such as moving `clearPending();` until after previous assignments. such alterations should be a separate PR with an *EXTREMELY* good reason as to why it needs be changed.

**Comment by Hackdom** [comment]
Will do. Checks effects then state changes though as far as the clear pending move in the one function

**Comment by Hackdom** [comment]
Looks like you fixed the create function though?

**Comment by gavofyork** [comment]
had a go with `create`, yeah. might also be worth using the fairly mature `SafeMath` contract rather than writing a new `plus` function.

**Comment by Hackdom** [comment]
That's my plus func, revised from SafeMath. I feel it's more robust than Zep's, and provides the error message. The lib is at https://www.github.com/Majoolr/ethereum-libraries.

**Comment by Hackdom** [comment]
Added proposals into different commits

**Pull request closed without merging**
