### PR TITLE
Move clearpending

### PR DESCRIPTION
**Pull request by Hackdom**
The clearpending function should be moved a smidge lower in the change owner function because it feels the workflow is more natural to clear the pending after effects have taken place. I would argue the addOwner function should be the same where clear pending is moved to just above the return in the second if and at the end of the function if all passes.

### CODE REVIEW

**Comment by barrywhitehat1** [comment]
Hi @Hackdom can you make PR to https://github.com/paritytech/contracts/tree/whg branch? Thats where the wallet fixes are going.

**Comment by Hackdom** [comment]
Done

**Comment by gavofyork** [comment]
i don't particularly agree with this one, but it is at least superficial so i'm happy to be overruled if the crowd.

personally, given i think it makes more sense to first clear the pending queue, then enact its effects, since the worst case of the latter is that an action doesn't happen when it should, whereas the worst case in the second is that it happens multiple times when it should only have happened once.

**Comment by Hackdom** [comment]
I can agree with your analysis, I'll close and let it reopen if need be

**Pull request closed without merging**
